### ISSUE TITLE
Blocks read

### ISSUE THREAD

**Issue by lrweck** [hairybreeches/pgMustard#18] opened 2019-10-04 13:37 UTC
I've found a problem with block counting:

![image](https://user-images.githubusercontent.com/26086198/66211643-d6827b80-e692-11e9-85ca-2d3720c14699.png)

Full explain: https://pastebin.com/D8tw2hj5

**Comment by hairybreeches** [comment] 2019-10-04 14:29
That doesn't look right. Sorry about that, I didn't think that would be possible. I'll have a dig into the causes on Monday and get back to you.

**Comment by hairybreeches** [comment] 2019-10-07 11:12
Hi Luis -

Just to update you with where we are on this, it looks like an issue where some blocks have been double counted in the query plan. I *think* this has happened because one of the nodes is an `InitPlan` node which is used both as itself _and_ as an input into another node.

We are taking this very seriously and are working on a way to identify when/how these blocks are double counted in the query plans, but it might take us a couple of days to do this.

Thanks for tipping us off about this issue.

Dave

**Comment by hairybreeches** [comment] 2019-10-15 13:09
Hi Luis -
We think we've got a fix for this issue, but unfortunately we believe that the postgres behaviour which causes it is version-dependent. 

We're waiting on confirmation from the postgres mailing lists, and if we're right we'll add a way for people to tell us which version of postgres they're using, and then we'll be able to deploy the fix (when applicable).

Thanks for bearing with us on this issue.

Dave

**Comment by hairybreeches** [comment] 2019-10-21 13:27
Hi Luis -

We've deployed a fix for this issue, let us know if you see any more similar problems like this in the future.

Thanks again for your patience with this one - it turned out to be a toughie!

This fix was added in commit 218d1bd957bf2d1187f689a76c3cb3c266b51367, deployed at 14:22 21/10/2019

**Closed by hairybreeches** 2019-10-21 13:27 UTC
Labels: bug

**Comment by lrweck** [comment] 2019-10-21 13:50
Great! I'll keep testing!
